logout:
  path: /logout

homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

guestbook_idex:
  path: /index
  defaults:  {_controller: AppBundle:Default:guestbookhp}

login:
  path: /login
  defaults: {_controller: AppBundle:Security:login}

guestbook_logged:
  path: /loggedin #soll mal /index im eingeloggten Zustand sein?
  defaults:  {_controller: AppBundle:Default:loggedin}

task_success:
  path: /task_success/{Name}/{Mail}/{Nachricht}
  defaults: {_controller: AppBundle:Default:sucsess}

beispiel:
  path: /beispiel
  defaults: { _controller: WebTechBundle:Beispiel:beispiel }

beispiel_template:
  path: /beispiel/template
  defaults: { _controller: WebTechBundle:Beispiel:beispielTemplate }


luckynumer:
  path: /luckynumber
  defaults: {_controller: WebTechBundle:Aufgabe1:luckyNumber}

name:
  path: /luckynumber/{name}
  defaults: {_controller: WebTechBundle:Aufgabe1:luckyNumber}

twigtest:
  path: /test/{name}
  defaults: {_controller: WebTechBundle:Aufgabe1:test}



